export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_PHYSICAL_WIDTH=113
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=85
export QT_QPA_EGLFS_ROTATION=90
export QT_QPA_EGLFS_WIDTH=640
export QT_QPA_EGLFS_HEIGHT=480
